<?php

/**
 * Contao Open Source CMS
 * 
 * Copyright (c) 2005-2014 Leo Feyer
 * 
 * Core translations are managed using Transifex. To create a new translation
 * or to help to maintain an existing one, please register at transifex.com.
 * 
 * @link http://help.transifex.com/intro/translating.html
 * @link https://www.transifex.com/projects/p/contao/language/de/
 * 
 * @license http://www.gnu.org/licenses/lgpl-3.0.html LGPL
 */

// system/modules/core/languages/de/tl_user_group.xlf
$GLOBALS['TL_LANG']['tl_user_group']['name'][0] = 'Titel';
$GLOBALS['TL_LANG']['tl_user_group']['name'][1] = 'Bitte geben Sie den Titel der Gruppe ein.';
$GLOBALS['TL_LANG']['tl_user_group']['alexf'][0] = 'Erlaubte Felder';
$GLOBALS['TL_LANG']['tl_user_group']['alexf'][1] = 'Hier können Sie festlegen, welche Felder bearbeitet werden dürfen.';
$GLOBALS['TL_LANG']['tl_user_group']['disable'][0] = 'Deaktivieren';
$GLOBALS['TL_LANG']['tl_user_group']['disable'][1] = 'Die Gruppe vorübergehend deaktivieren.';
$GLOBALS['TL_LANG']['tl_user_group']['start'][0] = 'Aktivieren am';
$GLOBALS['TL_LANG']['tl_user_group']['start'][1] = 'Die Gruppe automatisch an diesem Tag aktivieren.';
$GLOBALS['TL_LANG']['tl_user_group']['stop'][0] = 'Deaktivieren am';
$GLOBALS['TL_LANG']['tl_user_group']['stop'][1] = 'Die Gruppe automatisch an diesem Tag deaktivieren.';
$GLOBALS['TL_LANG']['tl_user_group']['title_legend'] = 'Titel';
$GLOBALS['TL_LANG']['tl_user_group']['modules_legend'] = 'Erlaubte Module';
$GLOBALS['TL_LANG']['tl_user_group']['pagemounts_legend'] = 'Pagemounts';
$GLOBALS['TL_LANG']['tl_user_group']['filemounts_legend'] = 'Filemounts';
$GLOBALS['TL_LANG']['tl_user_group']['forms_legend'] = 'Formular-Rechte';
$GLOBALS['TL_LANG']['tl_user_group']['account_legend'] = 'Konto-Einstellungen';
$GLOBALS['TL_LANG']['tl_user_group']['alexf_legend'] = 'Erlaubte Felder';
$GLOBALS['TL_LANG']['tl_user_group']['new'][0] = 'Neue Benutzergruppe';
$GLOBALS['TL_LANG']['tl_user_group']['new'][1] = 'Eine neue Benutzergruppe anlegen';
$GLOBALS['TL_LANG']['tl_user_group']['show'][0] = 'Gruppendetails';
$GLOBALS['TL_LANG']['tl_user_group']['show'][1] = 'Details der Gruppe ID %s anzeigen';
$GLOBALS['TL_LANG']['tl_user_group']['edit'][0] = 'Gruppe bearbeiten';
$GLOBALS['TL_LANG']['tl_user_group']['edit'][1] = 'Gruppe ID %s bearbeiten';
$GLOBALS['TL_LANG']['tl_user_group']['copy'][0] = 'Gruppe duplizieren';
$GLOBALS['TL_LANG']['tl_user_group']['copy'][1] = 'Gruppe ID %s duplizieren';
$GLOBALS['TL_LANG']['tl_user_group']['delete'][0] = 'Gruppe löschen';
$GLOBALS['TL_LANG']['tl_user_group']['delete'][1] = 'Gruppe ID %s löschen';
$GLOBALS['TL_LANG']['tl_user_group']['toggle'][0] = 'Gruppe aktivieren/deaktivieren';
$GLOBALS['TL_LANG']['tl_user_group']['toggle'][1] = 'Gruppe ID %s aktivieren/deaktivieren';

// system/modules/calendar/languages/de/tl_user_group.xlf
$GLOBALS['TL_LANG']['tl_user_group']['calendars_legend'] = 'Kalender-Rechte';

/**
 * TL_ROOT/system/modules/catalog/languages/de/tl_user_group.php 
 * 
 * TYPOlight extension: catalog 0.3.6 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2008 s.c.a.r.e., Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Joachim Scholtysik (jscholtysik) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user_group']['catalogs']['0'] = "Katalogtypen";
$GLOBALS['TL_LANG']['tl_user_group']['catalogs']['1'] = "Bitte wählen Sie die Katalogtypen aus, die Sie für die Benutzergruppe aktivieren möchten.";

// system/modules/faq/languages/de/tl_user_group.xlf
$GLOBALS['TL_LANG']['tl_user_group']['faq_legend'] = 'FAQ-Rechte';

// system/modules/news/languages/de/tl_user_group.xlf
$GLOBALS['TL_LANG']['tl_user_group']['news_legend'] = 'Nachrichten-Rechte';

// system/modules/newsletter/languages/de/tl_user_group.xlf
$GLOBALS['TL_LANG']['tl_user_group']['newsletter_legend'] = 'Newsletter-Rechte';
